apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusterversion-application
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: overlays/4.11.36
    repoURL: https://github.com/caseyrobb/cluster-version-gitops.git
    targetRevision: master
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
