apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patches:
- target:
    group: config.openshift.io
    version: v1
    kind: ClusterVersion
    name: version
  patch: |-
    - op: replace
      path: /spec/channel
      value: stable-4.11
    - op: replace
      path: /spec/desiredUpdate/version
      value: 4.11.44
